### ISSUE TITLE
Epic for refactoring

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#72]
e.g. quality output models

Proposal:

- rename this to QualityOutput (or QualityResponse depending on whether the respective input is named QualityRequest or QualityInput)
- rename QualityOutputModel to QualityRow
- remove QualityOutput dataclass and use QualityRow instead.

Further ToDo's:
- [x] MetaQS "Inhalte" is currently filtered for root ID, check again and return for each collection separately
- [x] Filtering for text is insufficient in the widgets, e.g., URL: please also add PDF’s
- [x] https://github.com/openeduhub/metaqs-main/issues/37
- [x] Als Fach noch “-Alle-” im WP einfügen (Root ID der Portale-Sammlung) -> CE
- [ ] Frontend Q-Matrix Header are flowing badly
- [x] Reenable timeline for all collections
- [ ] Show profile headers with grey background
- [x] "Material ohne Beschr.text": it shows Collections -_-
- [x] https://issues.edu-sharing.net/jira/browse/KBMBF-503
- [x] https://issues.edu-sharing.net/jira/browse/KBMBF-504
- [x] Where do I need to actually get source back? Does quality need this -> performance optimization
- [ ] Fixing broken collections without content
- [x] Refactor global storage, see https://github.com/openeduhub/metaqs-main/pull/69#discussion_r927460936
- [x] Refactor elastic search attribute objects: https://github.com/openeduhub/metaqs-main/issues/45
- [x] https://github.com/openeduhub/metaqs-main/issues/43

Questions
- [ ] s. https://confluence.edu-sharing.net/confluence/pages/resumedraft.action?draftId=83755373&draftShareId=7fb2f637-357d-4513-9ee7-048826e6f04a&
  - Abschnitt  **Erstes Zwischenzie** ...
	- "die Qualität der Füllung, welche künftig die KI durch grüne lächelnde oder rote mürrische Robots zeigt"
	- also kein Trend?

Consider:
- [x] https://github.com/openeduhub/metaqs-main/issues/64

**Comment by RMeissnerCC** [comment]
See: https://issues.edu-sharing.net/jira/browse/KBMBF-503

**Comment by RMeissnerCC** [comment]
172.18.0.2:55784 - "GET /api/collections/5e40e372-735c-4b17-bbf7-e827a5702b57/material_counts HTTP/1.1" 500
[2022-08-03 13:19:58 +0000] [9] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette_context/middleware/raw_middleware.py", line 96, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/app/api/api.py", line 317, in material_counts_tree
    return await get_material_count_tree(node_id)
  File "/app/app/api/collections/material_counts.py", line 156, in get_material_count_tree
    children = get_children(node_id=node_id)
  File "/app/app/api/collections/material_counts.py", line 143, in get_children
    return map_elastic_response_to_model(
  File "/app/app/api/collections/utils.py", line 15, in map_elastic_response_to_model
    return [model(**glom(hit.to_dict(), specs)) for hit in response]
  File "/app/app/api/collections/utils.py", line 15, in <listcomp>
    return [model(**glom(hit.to_dict(), specs)) for hit in response]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MissingMaterials
description
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by MRuecklCC** [comment]
@RMeissnerCC I would close this as done. I think the only remaining things are frontend issues.

**Comment by RMeissnerCC** [comment]
> @RMeissnerCC I would close this as done. I think the only remaining things are frontend issues.

Yes, let us close this issue. If changes are still wanted, we open a new issue.
